name: Daily API Call
on:
  schedule:
    # Cron is in UTC. If you are EST (UTC-5), 9 PM is 02:00 UTC.
    - cron: '0 2 * * *' 
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  post_calls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Script
        run: |
          chmod +x booking.sh
          ./booking.sh
