name: Daily API Call
on:
  schedule:
    # Cron is in UTC. If you are EST (UTC-5), 9 PM is 02:00 UTC.
    - cron: '30 15 * * *' 
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  post_calls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run booking script
        env:
          # This maps the GitHub Secret to a Shell Environment Variable
          CSRF_TOKEN: ${{ secrets.CSRF_TOKEN }}
          SESSION_ID: ${{ secrets.SESSION_ID }}
        run: |
          chmod +x booking.sh
          ./booking.sh
